version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
platform: x64
install:
  - git submodule update --init --recursive
before_build:
  - nuget restore
build:
  project: FFXIVMonReborn.sln
  parallel: true
  verbosity: normal
artifacts:
  - path: bin